package app.wiki.com.wikiapp;

public final class Constants {
    public static final String TAG = "WikiApp_DEBUG";
    public static final String DATA = "{\n"
            + "\"batchcomplete\": true,\n"
            + "\"continue\": {\n"
            + "\"gpsoffset\": 10,\n"
            + "\"continue\": \"gpsoffset||\"\n"
            + "},\n"
            + "\"query\": {\n"
            + "\"redirects\": [\n"
            + "{\n"
            + "\"index\": 4,\n"
            + "\"from\": \"Sachin Tyagi\",\n"
            + "\"to\": \"Solhah Singaarr\"\n"
            + "},\n"
            + "{\n"
            + "\"index\": 3,\n"
            + "\"from\": \"Sachin The Film\",\n"
            + "\"to\": \"Sachin: A Billion Dreams\"\n"
            + "}\n"
            + "],\n"
            + "\"pages\": [\n"
            + "{\n"
            + "\"pageid\": 57570,\n"
            + "\"ns\": 0,\n"
            + "\"title\": \"Sachin Tendulkar\",\n"
            + "\"index\": 1,\n"
            + "\"thumbnail\": {\n"
            + "\"source\": \"https://upload.wikimedia"
            + ".org/wikipedia/commons/thumb/2/25/Sachin_Tendulkar_at_MRF_Promotion_Event"
            + ".jpg/50px-Sachin_Tendulkar_at_MRF_Promotion_Event.jpg\",\n"
            + "\"width\": 50,\n"
            + "\"height\": 45\n"
            + "},\n"
            + "\"terms\": {\n"
            + "\"description\": [\n"
            + "\"former Indian cricketer\"\n"
            + "]\n"
            + "}\n"
            + "},\n"
            + "{\n"
            + "\"pageid\": 6957873,\n"
            + "\"ns\": 0,\n"
            + "\"title\": \"Sachin Pilot\",\n"
            + "\"index\": 6,\n"
            + "\"thumbnail\": {\n"
            + "\"source\": \"https://upload.wikimedia"
            + ".org/wikipedia/commons/thumb/b/bb"
            + "/Sachin_Pilot_at_the_India_Economic_Summit_2010_cropped"
            + ".jpg/39px-Sachin_Pilot_at_the_India_Economic_Summit_2010_cropped.jpg\",\n"
            + "\"width\": 39,\n"
            + "\"height\": 50\n"
            + "},\n"
            + "\"terms\": {\n"
            + "\"description\": [\n"
            + "\"Indian Politician, born 1977\"\n"
            + "]\n"
            + "}\n"
            + "},\n"
            + "{\n"
            + "\"pageid\": 10730502,\n"
            + "\"ns\": 0,\n"
            + "\"title\": \"Sachin (actor)\",\n"
            + "\"index\": 7,\n"
            + "\"thumbnail\": {\n"
            + "\"source\": \"https://upload.wikimedia"
            + ".org/wikipedia/commons/thumb/d/d9/SachinPilgaonkar.jpg/33px-SachinPilgaonkar"
            + ".jpg\",\n"
            + "\"width\": 33,\n"
            + "\"height\": 50\n"
            + "},\n"
            + "\"terms\": {\n"
            + "\"description\": [\n"
            + "\"Indian actor, director, producer, Writer, singer\"\n"
            + "]\n"
            + "}\n"
            + "},\n"
            + "{\n"
            + "\"pageid\": 11017085,\n"
            + "\"ns\": 0,\n"
            + "\"title\": \"Sachin Bhowmick\",\n"
            + "\"index\": 10,\n"
            + "\"terms\": {\n"
            + "\"description\": [\n"
            + "\"Film screenwriter and director\"\n"
            + "]\n"
            + "}\n"
            + "},\n"
            + "{\n"
            + "\"pageid\": 12355232,\n"
            + "\"ns\": 0,\n"
            + "\"title\": \"Solhah Singaarr\",\n"
            + "\"index\": 4,\n"
            + "\"terms\": {\n"
            + "\"description\": [\n"
            + "\"television series\"\n"
            + "]\n"
            + "}\n"
            + "},\n"
            + "{\n"
            + "\"pageid\": 20817418,\n"
            + "\"ns\": 0,\n"
            + "\"title\": \"Sachin Khedekar\",\n"
            + "\"index\": 8,\n"
            + "\"thumbnail\": {\n"
            + "\"source\": \"https://upload.wikimedia"
            + ".org/wikipedia/commons/thumb/6/65/Sachin_Khedekar.jpg/50px-Sachin_Khedekar.jpg\",\n"
            + "\"width\": 50,\n"
            + "\"height\": 38\n"
            + "},\n"
            + "\"terms\": {\n"
            + "\"description\": [\n"
            + "\"Indian actor\"\n"
            + "]\n"
            + "}\n"
            + "},\n"
            + "{\n"
            + "\"pageid\": 42182160,\n"
            + "\"ns\": 0,\n"
            + "\"title\": \"Sachin Bansal\",\n"
            + "\"index\": 9,\n"
            + "\"thumbnail\": {\n"
            + "\"source\": \"https://upload.wikimedia"
            + ".org/wikipedia/commons/thumb/8/84/Sachin_Bansal.jpg/36px-Sachin_Bansal.jpg\",\n"
            + "\"width\": 36,\n"
            + "\"height\": 50\n"
            + "},\n"
            + "\"terms\": {\n"
            + "\"description\": [\n"
            + "\"Indian Entrepreneur, founder and CEO of Flipkart.com\"\n"
            + "]\n"
            + "}\n"
            + "},\n"
            + "{\n"
            + "\"pageid\": 42382589,\n"
            + "\"ns\": 0,\n"
            + "\"title\": \"Sachin! Tendulkar Alla\",\n"
            + "\"index\": 2,\n"
            + "\"terms\": {\n"
            + "\"description\": [\n"
            + "\"2014 film by Mohan Shankar\"\n"
            + "]\n"
            + "}\n"
            + "},\n"
            + "{\n"
            + "\"pageid\": 50125865,\n"
            + "\"ns\": 0,\n"
            + "\"title\": \"Sachin: A Billion Dreams\",\n"
            + "\"index\": 3,\n"
            + "\"terms\": {\n"
            + "\"description\": [\n"
            + "\"2017 Indian biographical film directed by James Erskine\"\n"
            + "]\n"
            + "}\n"
            + "},\n"
            + "{\n"
            + "\"pageid\": 53197293,\n"
            + "\"ns\": 0,\n"
            + "\"title\": \"Sachintha Peiris\",\n"
            + "\"index\": 5,\n"
            + "\"terms\": {\n"
            + "\"description\": [\n"
            + "\"cricketer\"\n"
            + "]\n"
            + "}\n"
            + "}\n"
            + "]\n"
            + "}\n"
            + "}";
    private Constants() {
    }
}
